"""
Slack chat-bot Lambda handler.
"""

import os
import logging
import urllib
import random

# Grab the Bot OAuth tokens from the environment.
BOT_TOKEN = os.environ["BOT_TOKEN"]
ACCESS_TOKEN = os.environ["ACCESS_TOKEN"]

# Define the URL of the targeted Slack API resource.
# We'll send our replies there.
SLACK_URL = "https://slack.com/api/chat.postMessage"

# List Lunch venues
venues =   ["Betty's",
            "Beach House",
            "Grill'd",
            "Dodgy curry",
            "Casa Cibo",
            "Zeus",
            "Motto Motto",
            "Hermosa",
            "Slightly less dodgy curry"
            ]


def lambda_handler(data, context):
    """
    Handle an incoming HTTP request from a Slack chat-bot.
    """
    
    if "challenge" in data:
        return data["challenge"]
        
    # Grab the Slack event data.
    slack_event = data['event']
    token = data['token']
    
    print (slack_event)
    
    # Verify origin is bot
    if token != ACCESS_TOKEN:
        logging.warn("Ignore bot event")
    
    # We need to discriminate between events generated by 
    # the users, which we want to process and handle, 
    # and those generated by the bot.
    if "bot_id" in slack_event:
        logging.warn("Ignore bot event")
    else:
        # Get the text of the message the user sent to the bot,
        # and reverse it, or
        text = slack_event["text"]
        response_text = text[::-1]
        
        # Pick a luch venue
        if "lunch" in str.lower(text) and "?" in str.lower(text):
            venue = random.choice(venues) 
            response_text = venue
            
        # Get the ID of the channel where the message was posted.
        channel_id = slack_event["channel"]
        
        # We need to send back three pieces of information:
        #     1. The response text (text)
        #     2. The channel id of the private, direct chat (channel)
        #     3. The OAuth token required to communicate with 
        #        the API (token)
        # Then, create an associative array and URL-encode it.
        data = urllib.parse.urlencode(
            (
                ("token", BOT_TOKEN),
                ("channel", channel_id),
                ("text", response_text)
            )
        )
        data = data.encode("ascii")
        
        # Construct the HTTP request that will be sent to the Slack API.
        request = urllib.request.Request(
            SLACK_URL, 
            data=data, 
            method="POST"
        )
        # Add a header mentioning that the text is URL-encoded.
        request.add_header(
            "Content-Type", 
            "application/x-www-form-urlencoded"
        )
        
        # Fire off the request!
        urllib.request.urlopen(request).read()

    # Everything went fine.
    return "200 OK"
